#!/bin/bash

# Can be defined in .bashrc, use "readonly backupDir"
export backupDir = $HOME/.backup/

if [ -d $1 ]
then
    export filename = $1_$(date +%y%m%d)
    7z -tzip a $filename $1/
    if [ $2 != "" ]
    then
        mv $filename $2/
    else
        mv $filename $backupDir
    fi
else
    export filename = $1_$(date +%y%m%d).backup
    if [ $2 != "" ]
    then
        # Use specified directory
        cp $1 $2/$filename
    else
        # Use default directory
        cp $1 $backupDir/$filename
    fi
fi
