#!/bin/bash

ask_yn() {
    prompt="$1"
    while true; do
        read -rp "$prompt [y/n] " yn || exit
        if [ "$yn" = "y" ] || [ "$yn" = "Y" ]; then
            return 0
        elif [ "$yn" = "n" ] || [ "$yn" = "N" ]; then
            return 1
        fi
        echo "Please enter either Y or N."
    done
}

if ask_yn "Do stuff?"; then
    echo "Doing stuff..."
else
    echo "Nevermind..."
fi
